In [1]:
import pandas as pd

In [37]:
an = pd.read_csv('./anisio_WQOLFisico.csv')

In [38]:
an

,WHOQoL_1,WHOQoL_2,WHOQoL_3,WHOQoL_4,WHOQoL_5,WHOQoL_6,WHOQoL_7,WHOQoL_8,WHOQoL_9,WHOQoL_10,...,WHOQoL_18,WHOQoL_19,WHOQoL_20,WHOQoL_21,WHOQoL_22,WHOQoL_23,WHOQoL_24,WHOQoL_25,WHOQoL_26,WQOL.Fisico
0,4.0,4.0,1.0,1.0,4.0,5.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,4.285714
1,2.0,4.0,3.0,2.0,3.0,4.0,3.0,2.0,4.0,3.0,...,2.0,3.0,2.0,2.0,3.0,4.0,3.0,4.0,2.0,2.857143
2,5.0,4.0,1.0,1.0,3.0,3.0,3.0,4.0,5.0,4.0,...,1.0,4.0,3.0,3.0,3.0,4.0,5.0,5.0,2.0,3.428571
3,4.0,3.0,2.0,3.0,3.0,4.0,3.0,3.0,2.0,3.0,...,4.0,3.0,4.0,4.0,3.0,5.0,5.0,5.0,2.0,3.714286
4,2.0,2.0,3.0,3.0,2.0,4.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,1.0,4.0,4.0,4.0,4.0,2.0,3.285714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148412,4.0,3.0,1.0,2.0,2.0,2.0,3.0,2.0,4.0,3.0,...,3.0,3.0,3.0,2.0,4.0,4.0,4.0,4.0,2.0,3.857143
148413,3.0,3.0,2.0,2.0,3.0,4.0,2.0,3.0,2.0,3.0,...,2.0,3.0,3.0,1.0,4.0,4.0,1.0,2.0,2.0,3.142857
148414,2.0,2.0,4.0,3.0,2.0,2.0,3.0,3.0,4.0,1.0,...,3.0,2.0,1.0,3.0,4.0,4.0,4.0,4.0,4.0,2.142857
148415,1.0,1.0,2.0,1.0,4.0,4.0,5.0,5.0,5.0,4.0,...,4.0,5.0,5.0,4.0,4.0,5.0,4.0,5.0,1.0,4.285714
148416,4.0,5.0,1.0,2.0,4.0,4.0,4.0,4.0,3.0,5.0,...,4.0,4.0,4.0,4.0,4.0,5.0,4.0,4.0,2.0,4.571429

In [39]:
an.to_csv('./anisio_WQOLFisico2.csv', index=False, sep=' ', header=False)

In [28]:
import numpy as np

In [35]:
pd.DataFrame(np.zeros((26,26))).to_csv('./an_net.txt', index=False, sep=',', header=False)

In [12]:
an = pd.read_csv('./anisio_WQOLFisico2.csv')

In [13]:
an

       4.0\t4.0\t1.0\t1.0\t4.0\t5.0\t4.0\t4.0\t4.0\t4.0\t3.0\t3.0\t3.0\t4.0\t4.0\t4.0\t4.0\t4.0\t4.0\t4.0\t4.0\t4.0\t4.0\t4.0\t1.0\t4.285714285714286
0       2.0\t4.0\t3.0\t2.0\t3.0\t4.0\t3.0\t2.0\t4.0\t3...
1       5.0\t4.0\t1.0\t1.0\t3.0\t3.0\t3.0\t4.0\t5.0\t4...
2       4.0\t3.0\t2.0\t3.0\t3.0\t4.0\t3.0\t3.0\t2.0\t3...
3       2.0\t2.0\t3.0\t3.0\t2.0\t4.0\t3.0\t3.0\t3.0\t3...
4       5.0\t5.0\t3.0\t2.0\t4.0\t4.0\t3.0\t4.0\t4.0\t4...
...                                                   ...
148411  4.0\t3.0\t1.0\t2.0\t2.0\t2.0\t3.0\t2.0\t4.0\t3...
148412  3.0\t3.0\t2.0\t2.0\t3.0\t4.0\t2.0\t3.0\t2.0\t3...
148413  2.0\t2.0\t4.0\t3.0\t2.0\t2.0\t3.0\t3.0\t4.0\t1...
148414  1.0\t1.0\t2.0\t1.0\t4.0\t4.0\t5.0\t5.0\t5.0\t4...
148415  4.0\t5.0\t1.0\t2.0\t4.0\t4.0\t4.0\t4.0\t3.0\t5...

[148416 rows x 1 columns]